(ns services.countries)
(def countries {
                 :AGO "Angola"
                 :BEN "Benin"
                 :BWA "Botswana"
                 :BFA "Burkina Faso"
                 :BDI "Burundi"
                 :CMR "Cameroon"
                 :TCD "Chad"
                 :COM "Comoros"
                 :COG "Congo"
                 :DJI "Djibouti"
                 :EGY "Egypt"
                 :ETH "Ethiopia"
                 :GAB "Gabon"
                 :GMB "Gambia"
                 :GHA "Ghana"
                 :GIN "Guinea"
                 :CIV "Ivory Coast"
                 :KEN "Kenya"
                 :LSO "Lesotho"
                 :LBR "Liberia"
                 :MDG "Madagascar"
                 :MWI "Malawi"
                 :MLI "Mali"
                 :MRT "Mauritania"
                 :MUS "Mauritius"
                 :MAR "Morocco"
                 :MOZ "Mozambique"
                 :NAM "Namibia"
                 :NER "Niger"
                 :NGA "Nigeria"
                 :REU "Reunion"
                 :RWA "Rwanda"
                 :SEN "Senegal"
                 :SYC "Seychelles"
                 :SLE "Sierra Leone"
                 :SOM "Somalia"
                 :ZAF "South Africa"
                 :SDN "Sudan"
                 :SWZ "Swaziland"
                 :TZA "Tanzania"
                 :TGO "Togo"
                 :TUN "Tunisia"
                 :UGA "Uganda"
                 :ZAR "Zaire"
                 :ZMB "Zambia"
                 :ZWE "Zimbabwe"
                 :BHS "Bahamas"
                 :BRB "Barbados"
                 :BLZ "Belize"
                 :CAN "Canada"
                 :CRI "Costa Rica"
                 :DMA "Dominica"
                 :DOM "Dominican Rep."
                 :SLV "El Salvador"
                 :GRD "Grenada"
                 :GTM "Guatemala"
                 :HTI "Haiti"
                 :HND "Honduras"
                 :JAM "Jamaica"
                 :MEX "Mexico"
                 :NIC "Nicaragua"
                 :PAN "Panama"
                 :PRI "Puerto Rico"
                 :KNA "Saint Kitts & Nevis"
                 :LCA "Saint Lucia"
                 :VCT "Saint Vincent & Grenadines"
                 :TTO "Trinidad & Tobago"
                 :USA "United States of America"
                 :ARG "Argentina"
                 :BOL "Bolivia"
                 :BRA "Brazil"
                 :CHL "Chile"
                 :COL "Colombia"
                 :ECU "Ecuador"
                 :GUY "Guyana"
                 :PRY "Paraguay"
                 :PER "Peru"
                 :SUR "Suriname"
                 :URY "Uruguay"
                 :VEN "Venezuela"
                 :BHR "Bahrain"
                 :BGD "Bangladesh"
                 :BTN "Bhutan"
                 :CHN "China"
                 :HKG "Hong Kong"
                 :IND "India"
                 :IDN "Indonesia"
                 :IRN "Iran"
                 :IRQ "Iraq"
                 :ISR "Israel"
                 :JPN "Japan"
                 :JOR "Jordan"
                 :KOR "Korea, Rep. (South)"
                 :KWT "Kuwait"
                 :LAO "Laos"
                 :MYS "Malaysia"
                 :MNG "Mongolia"
                 :MMR "Myanmar"
                 :NPL "Nepal"
                 :OMN "Oman"
                 :PAK "Pakistan"
                 :PHL "Philippines"
                 :QAT "Qatar"
                 :SAU "Saudi Arabia"
                 :SGP "Singapore"
                 :LKA "Sri Lanka"
                 :SYR "Syria"
                 :TWN "Taiwan"
                 :THA "Thailand"
                 :ARE "United Arab E."
                 :YEM "Yemen"
                 :AUT "Austria"
                 :BEL "Belgium"
                 :BGR "Bulgaria"
                 :CYP "Cyprus"
                 :CSK "Czechoslovakia"
                 :DNK "Denmark"
                 :FIN "Finland"
                 :FRA "France"
                 :GER "Germany"
                 :GRC "Greece"
                 :HUN "Hungary"
                 :ISL "Iceland"
                 :IRL "Ireland"
                 :ITA "Italy"
                 :LUX "Luxembourg"
                 :MLT "Malta"
                 :NLD "Netherlands"
                 :NOR "Norway"
                 :POL "Poland"
                 :PRT "Portugal"
                 :ROM "Romania"
                 :RUS "Russia"
                 :ESP "Spain"
                 :SWE "Sweden"
                 :CHE "Switzerland"
                 :TUR "Turkey"
                 :YUG "Yugoslavia"
                 :GBR "United Kingdom"
                 :AUS "Australia"
                 :FJI "Fiji"
                 :NZL "New Zealand"
                 :TON "Tonga"
                 :VUT "Vanuatu"
                 :WSM "Western Samoa"})